### ISSUE TITLE
Alternative colors: layer in mobile layout with wrong color

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#552]
For the first three colors schemes it works  - it looks like this (second alternative color): 

![screenshot 2015-09-30 18 05 10](https://cloud.githubusercontent.com/assets/5286499/10199381/b829f08e-67a0-11e5-89fd-8d96e8ca6129.png)

For the third and fourth alternative color - it's wrong:
![screenshot 2015-09-30 18 03 54](https://cloud.githubusercontent.com/assets/5286499/10199484/32a2225a-67a1-11e5-8bd2-8d5067a1a437.png)

![screenshot 2015-09-30 18 05 09](https://cloud.githubusercontent.com/assets/5286499/10199514/539c99d6-67a1-11e5-9042-13c45832f3a1.png)

**Comment by gjb2048** [comment]
Ok, given that the background is a gradient which is no longer in the theme, is this an oddity of your installation?

**Comment by gjb2048** [comment]
Ok, something very odd is happening here.

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_essential/commit/c6b55f268eabec8a83b3de32c9d4e6e626a1bd74

**Comment by relecand** [comment]
Hm - problem is still there - when the themes switches to mobile layout.

**Comment by relecand** [comment]
![screenshot 2015-09-30 19 08 28](https://cloud.githubusercontent.com/assets/5286499/10200437/c0139ee8-67a6-11e5-9735-ce0632feafd6.png)

**Comment by relecand** [comment]
Wait ... must switch the branch

**Comment by relecand** [comment]
Ok, everything is fine - just checked out the MOODLE_29 branch. Thank you!

**Comment by gjb2048** [comment]
I'll update master soon.
