### ISSUE TITLE
Block tree node icons in RTL mode are slightly off

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#666]
![image](https://cloud.githubusercontent.com/assets/231168/15773341/1379d88c-297f-11e6-9ea9-6b8a4eb019fd.png)

Removing "margin-right:0;" solves it.

**Comment by gjb2048** [comment]
What version of Essential please Nadav?

**Comment by nadavkav** [comment]
3.0.1.3 (Build: 2016010206)

It's a demo system with the latest themes
http://themes.moodlemagic.info/
If you'd login I will give you Admin permissions, so you can explore RTL content I upload for testing.

**Comment by gjb2048** [comment]
Cannot reproduce, probably down to a mistake I made and corrected here: https://github.com/gjb2048/moodle-theme_essential/commit/9fedbf4f0990a4a0d2527342de253730a36abf01

**Comment by nadavkav** [comment]
Update to latest master and still have this issue

Applying the following code fixes it:
.block_settings .block_tree p.hasicon {
    text-indent: 0;
}
For both LTR and RTL.

Related issue... 
The missing aria-hidden = true FA icons
I used the following code to fix that too:
.hasicon [aria-hidden="true"] {
    display: inline-block !important;
}

Indeed, they are different issues, but very close related.
What do you think about the fix?

And btw...
Can you help me find the LESS code that is generating:
.dir-rtl .block_settings .block_tree .tree_item img

**Comment by nadavkav** [comment]
I have this issue on two different servers (fresh install of Moodle 3.1)

**Comment by gjb2048** [comment]
I thought you were running M3.0?

**Comment by gjb2048** [comment]
Cannot reproduce on M3.0:

![2016-06-08 18_45_18- _ topics](https://cloud.githubusercontent.com/assets/1058419/15904522/44113cbe-2da9-11e6-81c9-011203e67f7b.png)

![2016-06-08 18_46_28- _ topics](https://cloud.githubusercontent.com/assets/1058419/15904568/68edf392-2da9-11e6-805c-05ae5ae9f85c.png)

**Comment by nadavkav** [comment]
Sorry if I confused you.
Indeed. looks fine on 3.0

**Comment by gjb2048** [comment]
Ok, I'll deal with M3.1 issues when the time comes.
