### ISSUE TITLE
Main content does not expand

### ISSUE THREAD

**Issue by athasdos** [gjb2048/moodle-theme_essential#724]
Hi Gareth,

After the 3.0.1.7 update, when the blocks in block-region-side-pre/post are moved to the dock or just moved to one of the block-region-side-pre/post , the main content doesn't expand. In the standard or essential layout, the left or right side will have an empty space where the main content should have been expanded.
Is this due to the new "Page top" blocks? Any way of disabling it?

Thanks as always for this great theme.
Sincerely,
Francisco

![capture](https://cloud.githubusercontent.com/assets/21199299/17898263/b9e04116-691c-11e6-807c-3d8bfd138af8.JPG)
![capture2](https://cloud.githubusercontent.com/assets/21199299/17898295/d9bd230a-691c-11e6-9954-d5a65f14e7a3.JPG)

**Comment by gjb2048** [comment]
This was fixed in #711 and is in 3.1.0.7.  Try 'Purging all caches'.

**Comment by athasdos** [comment]
Thanks for your prompt answer....I did purge the all the cache, but I am still getting the same result. 

When I dock all the blocks, the main content is expanded, but as you can see in my screenshots, my blocks are not docked, they are just move into one of the side columns.  

Thanks again,
Francisco

**Comment by gjb2048** [comment]
Odd.  Ok, not down to the page top block addition.  That looks like the side-pre region with no content.

**Comment by athasdos** [comment]
I apologize if I am not clear since English is not my native language, and I am confused with your last post.

Just so I can clarify....the blocks do not get moved automatically to one column. I moved intentionally all the blocks from the left column (block-region-side-pre) to the right column (block-region-side-post). This is what it cause the gap between the main content and the side region.

***I will be happy to provide you access to my demo site.

Sincerely,
Francisco

**Comment by gjb2048** [comment]
Summary: I need to investigate.

**Comment by artur-moreira** [comment]
I'm having the same issue after upgrading to 3.1.0.7+

The actual page:
![image](https://cloud.githubusercontent.com/assets/20660925/17903235/9cb9d084-6962-11e6-96d9-de2b239294b1.png)

This fix the problem (it's similar to previous versions tags):
![image](https://cloud.githubusercontent.com/assets/20660925/17903136/44f701dc-6962-11e6-8a16-97c38d66e054.png)

**Comment by gjb2048** [comment]
There is method in my madness.  This is more complex than you think.  That solution will not be the complete answer.  Please give me time to fix this.

**Comment by gjb2048** [comment]
M3.0-?

**Comment by athasdos** [comment]
My moodle version is 3.1

**Comment by gjb2048** [comment]
@athasdos Fair enough, but 'M3.0-?' was a note for me to check the M3.0 and 2.9 versions for the same issue.

**Comment by gjb2048** [comment]
Umm, @athasdos - you originally stated that you are using version 3.1 and yet you write 'After the 3.0.1.7 update' - therefore why are you using the M3.0 version on M3.1?

**Comment by athasdos** [comment]
Sorry, I was referring to essential 3.1.0.7 (Build: 2016061706) (2016061706), Moodle 3.1....I am not using Moodle 3.0

**Comment by gjb2048** [comment]
Ok thanks.  But please be precise in future as wrong detail can waste lots of time.

**Comment by alexmuellerITS** [comment]
Hi Gareth, We are having the same problem as well. Have purged all caches. 
![essentials 3 1 0 7 issue](https://cloud.githubusercontent.com/assets/21218386/17928489/3b54b430-6a3e-11e6-9c50-e83f70725526.JPG)

**Comment by gjb2048** [comment]
@alexmuellerITS - fixed in https://github.com/gjb2048/moodle-theme_essential/commit/fab1c8cddcb85cb6d436404e80a309e080d7140f as above and will be backported in due course.

**Comment by alexmuellerITS** [comment]
You are awesome Gareth. Thanks again :)

 

Alex Mueller
Chief Executive Officer

Intelligent Training Solutions Pty Ltd 

 


RTO TOID: 22570

Unit 9 / 62-64 Oakover Road, Preston, Victoria 3076 Australia
T: 03 9351 1068 | M: 0416 131 231
E:  <mailto:alex@its.vic.edu.au> alex@its.vic.edu.au |  W:  <http://www.its.vic.edu.au> www.its.vic.edu.au | W:  <http://www.its.vic.edu.au/itsdrive> www.its.vic.edu.au/itsdrive | I:  <mailto:info@its.vic.edu.au> info@its.vic.edu.au 

P Please consider the environment before you print this email.

This email and any attachments may be confidential.  If received in error, please contact us and delete all copies. Before opening or using attachments check for viruses and defects.  Regardless of loss, damage or consequence, whether caused by negligence of the sender or not, resulting directly or indirectly from the use of any attached files our liability is limited to resupplying and affected attachments.  Any representatives or opinions expressed are those of the individual sender, and not necessarily those of Intelligent Training Solutions Pty Ltd.

 

This communication may be used as evidence in auditing of the AQTF standards and Standards for RTOs. Authorised parties include Intelligent Training Solutions Pty Ltd, Skills Victoria or National Training Service (Registered RTO).
